---
title: "MA304_2322905"
author: "Ajinkya_Thokal(2322905)"
date: "2024-04-18"
output:
  html_document:
    df_print: paged
  word_document: default
  self_contained: false
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, include = TRUE, warning = FALSE, message = FALSE, comment = NA)
```


```{r , warning=FALSE, comment= " ", message= FALSE}
# packages we need
library(ggplot2)
library(tidyr)
library(plotly)
library(leaflet)

```

```{r, comment= " "}
# Read the dataset
colchester_data <- read.csv("crime23.csv")


# Summary table
summary_table <- table(colchester_data$category)
summary_table <- sort(summary_table, decreasing = TRUE)
summary_table


```

```{r}
# Pie chart
# Define custom colors
custom_colors <- c("steelblue", "darkorange", "forestgreen", "firebrick", "mediumslateblue",
                         "sienna", "orchid", "dimgray", "olivedrab", "dodgerblue",
                         "lightsteelblue", "peachpuff", "palegreen", "lightsalmon")


pie_chart <- ggplot(colchester_data, aes(x = "", fill = category)) +
  geom_bar(width = 1, color = "black") + 
  # Create a bar chart
  coord_polar("y") +  # Convert to polar coordinates
  labs(title = "Distribution of Crime Categories in Colchester",
       fill = "Category") +
  scale_fill_manual(values = custom_colors)+
  theme_void() +  # Remove unnecessary elements
  theme(legend.position = "right")  

# Display the pie chart
print(pie_chart)
```

```{r}
# Create histogram
histogram <- ggplot(colchester_data, aes(x = category)) +
  geom_bar(fill = "lightgreen", color = "black", alpha = 0.7, position = "dodge") +  # Adjust colors and position
  labs(title = "Histogram of Crime Categories in Colchester",
       x = "Category",
       y = "Count") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Let's convert ggplot to plotly
interactive_histogram <- ggplotly(histogram)

# Display the interactive plot
interactive_histogram
```

```{r}
# Box plot

boxplot <- ggplot(colchester_data, aes(x = category, y = lat)) +
  geom_boxplot(fill = "lightblue", color = "black") +  # Customize box plot aesthetics
  labs(title = "Box Plot of Crime Categories in Colchester",
       x = "Category",
       y = "Latitude") +  # Added informative labels
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  

# Convert ggplot to plotly
interactive_boxplot <- ggplotly(boxplot)

# Display the interactive plot
interactive_boxplot
```

```{r}
# Scatter plot

scatter_plot <- ggplot(colchester_data, aes(x = long, y = lat)) +
  geom_point(alpha = 0.5, color = "blue") + 
  geom_smooth(method = "lm", se = FALSE, color = "red") + # Adjusted point aesthetics
  labs(title = "Scatter Plot of Crime Locations in Colchester",
       x = "Longitude",
       y = "Latitude") +  # Added informative labels
  theme_minimal()

# Making it interactive
plotly <- ggplotly(scatter_plot)
plotly

```

```{r , comment= " "}
# Calculate correlation coefficient
correlation_coefficient <- cor(colchester_data$lat, colchester_data$long)

# Print correlation coefficient
print(correlation_coefficient)
```

```{r}
#time series plot

# Let's convert date to Date format
colchester_data$date <- as.Date(paste(colchester_data$date, "-01", sep = ""), format = "%Y-%m-%d")

# Plotting

ggplot(colchester_data, aes(x = date)) +
  geom_bar(stat = "count", fill = "maroon") +
  labs(title = "Crime Occurrences Over Time",
       x = "Date",
       y = "Count") +
  theme_minimal()
```

```{r}

# Leaflet

# Let's create Leaflet map
crime_map <- leaflet() %>%
addTiles() %>%
setView(lng = 0.909136, lat = 51.88306, zoom = 12) # We have adjusted the zoom

# Let's add markers for crime locations
crime_map <- crime_map %>%
addMarkers(data = colchester_data,
lng = ~long,
lat = ~lat,
popup = ~paste("Category:", category, "<br>Date:", date))

# Print the map
crime_map
```



